# This is a basic workflow to help you get started with Actions
# source: https://unity-ci.com/docs/github/getting-started

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events on specified branch
  # pull_request: {}
  # push: { branches: [develop, main] }

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    # name: Build LegoDodgeBall
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.4.15f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.4.15f1
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
